### ISSUE TITLE
NmzDeg1Elements returns different outputs.

### ISSUE THREAD

**Issue by kamalsaleh** [gap-packages/NormalizInterface#58]
I am searching for the deg 1 elements of the hilbert basis of the cone defined in R^3 by the generators 
[ [**0,0**,_1_], [**0,2**,_1_], [**1,0**,_1_], [**1,1**,_1_] ].

When I use normaliz with input file

```
amb_space 3
cone 4
0 0 1
0 2 1
1 0 1
1 1 1
Deg1Elements
```

I get

```
5 Hilbert basis elements of degree 1:
 0 0 1
 0 1 1
 0 2 1
 1 0 1
 1 1 1
```

from which I can read off the lattice points { [0,0], [0,1], [0,2],[1,0], [1,1] } inside the polytope given by the vertices **[ [0,0], [0,2], [1,0], [1,1] ]**.

Now when I try to compute that in NormalizInterface, I get:
```

C := NmzCone( "integral_closure", [ [0,0,1], [0,2,1], [1,0,1], [1,1,1] ] );
NmzDeg1Elements(C);
[ [ 0, 0, 1 ], [ 1, 0, 1 ] ] 
```
But if we ask first for the hilbert basis, we get a different answer:
```

D := NmzCone( "integral_closure", [ [0,0,1], [0,2,1], [1,0,1], [1,1,1] ] );
NmzHilbertBasis(D);
[ [ 0, 0, 1 ], [ 0, 1, 1 ], [ 0, 2, 1 ], [ 1, 0, 1 ], [ 1, 1, 1 ] ] 
NmzDeg1Elements(D);
[ [ 0, 0, 1 ], [ 0, 1, 1 ], [ 0, 2, 1 ], [ 1, 0, 1 ], [ 1, 1, 1 ] ] 
```

**Comment by kamalsaleh** [comment]
@sebasguts

**Comment by fingolfin** [comment]
@kamalsaleh With which version of normaliz did you produce your examples above?

I just tested, and with NormalizInterface built against Normaliz 3.7.2, I get this (which I think is what you wanted?)
```
gap> C := NmzCone( "integral_closure", [ [0,0,1], [0,2,1], [1,0,1], [1,1,1] ] );
<a Normaliz cone>
gap> NmzDeg1Elements(C);
[ [ 0, 0, 1 ], [ 0, 1, 1 ], [ 0, 2, 1 ], [ 1, 0, 1 ], [ 1, 1, 1 ] ]
gap> D := NmzCone( "integral_closure", [ [0,0,1], [0,2,1], [1,0,1], [1,1,1] ] );
<a Normaliz cone>
gap> NmzHilbertBasis(D);
[ [ 0, 0, 1 ], [ 0, 1, 1 ], [ 0, 2, 1 ], [ 1, 0, 1 ], [ 1, 1, 1 ] ]
gap> NmzDeg1Elements(D);
[ [ 0, 0, 1 ], [ 0, 1, 1 ], [ 0, 2, 1 ], [ 1, 0, 1 ], [ 1, 1, 1 ] ]
```

**Comment by kamalsaleh** [comment]
@fingolfin I can reproduce the error with normaliz 3.5.1 and NormalizInterface 1.0.2. Your code with the current versions is exactly what one would expect. I think this issue can thus be closed.

**Comment by fingolfin** [comment]
I'll close it once a version of NormalizInterface where this is actually fixed by default is released (i.e. built against 3.7.2), or at least has been committed. In the meantime, it's good to be reminded about this.

**Comment by fingolfin** [comment]
@kamalsaleh hmm, I actually just tried this with normaliz 3.5.1, and could *not* reproduce the problem, at least not on master (I did not try with NormalizInterface 1.0.2).

**Comment by kamalsaleh** [comment]
I can still reproduce it on plesken-server where the default installation of NormalizInterface is still 1.0.2.

**Comment by fingolfin** [comment]
@kamalsaleh yeah but what is the version of Normaliz?

**Comment by kamalsaleh** [comment]
Normaliz that is being used there is on this commit `fdf877804e473a4f59e3b20465598f97088fb547` with version v3.1.1.

**Comment by fingolfin** [comment]
Wait, with 3.1.1? Is that a typo?

**Comment by kamalsaleh** [comment]
As I see in the `update.sh` script in `/opt/gap/gap_pkg`, the update happens like this: 1- pull NormalizInterface, 2- configure, 3- make. Hence the included Normaliz.git will never be updated. Hence, the version of normaliz is still 3.1.1 from 2016 on commit `fdf877804e473a4f`. The update.sh file should be updated taking into consideration running the script `build-normaliz.sh` first.

**Comment by fingolfin** [comment]
I know nothing about this update.sh script, so I can't comment on that. But NormalizInterface 1.0.2 requires Normaliz >= 3.4.0, so it shouldn't even compile in the situation you describe

**Comment by kamalsaleh** [comment]
In the server, there is two `pkg` directories, the default `gap-4.10.2/pkg/` directory and an external one. Both have NormalizInterface.

The default: has NormalizInterface 1.0.2 with Normaliz v3.4.0.
The external: has NormalizInterface 1.0.1 with Normaliz v3.1.1. 

The package that loads from gap is the newest available version, i.e., 1.0.2.  and the error can still be reproduced there. 

Now I see, my response with v3.1.1 came after I checked the external `pkg `directory, which is -supposed to be- updated on a regular basis.

**Comment by fingolfin** [comment]
Fixed in NormalizInterface 1.1.0, which comes with Normaliz 3.5.4
